/* The following code was generated by JFlex 1.7.0 */

/*
  JFlex scanner for NanoMorpho

  Based on Snorri Agnarssons NanoLisp scanner.

  Authors:  Hjalti Geir Garðarsson
            Egill Ragnarsson
            Guðmundur Óli Norland
  
  Running the program:
    Compile:
      java -jar JFlex-full-1.7.0.jar nanomorpho.jflex
      javac NanoMorpho.java
    Run:
      java NanoMorpho <input_file> > <output_file>
  
  Use the makefile:
*/

import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>nanomorpho.jflex</tt>
 */
public class NanoMorpho {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\41\1\35\1\37\1\40\1\36\22\0\1\41\1\26\1\20"+
    "\2\0\2\26\1\21\2\24\1\26\1\4\1\24\1\4\1\2\1\26"+
    "\4\22\4\23\2\1\1\26\1\34\1\26\1\27\2\26\1\0\4\25"+
    "\1\3\25\25\1\0\1\15\1\0\1\26\1\25\1\0\1\12\1\16"+
    "\2\25\1\10\1\11\1\25\1\32\1\33\2\25\1\13\1\25\1\17"+
    "\3\25\1\6\1\14\1\5\1\7\1\30\1\31\3\25\1\24\1\26"+
    "\1\24\1\26\6\0\1\37\44\0\1\25\12\0\1\25\4\0\1\25"+
    "\5\0\27\25\1\0\37\25\1\0\u01ca\25\4\0\14\25\16\0\5\25"+
    "\7\0\1\25\1\0\1\25\201\0\5\25\1\0\2\25\2\0\4\25"+
    "\1\0\1\25\6\0\1\25\1\0\3\25\1\0\1\25\1\0\24\25"+
    "\1\0\123\25\1\0\213\25\10\0\246\25\1\0\46\25\2\0\1\25"+
    "\7\0\47\25\110\0\33\25\5\0\3\25\55\0\53\25\43\0\2\25"+
    "\1\0\143\25\1\0\1\25\17\0\2\25\7\0\2\25\12\0\3\25"+
    "\2\0\1\25\20\0\1\25\1\0\36\25\35\0\131\25\13\0\1\25"+
    "\30\0\41\25\11\0\2\25\4\0\1\25\5\0\26\25\4\0\1\25"+
    "\11\0\1\25\3\0\1\25\27\0\31\25\107\0\25\25\1\0\10\25"+
    "\106\0\66\25\3\0\1\25\22\0\1\25\7\0\12\25\17\0\20\25"+
    "\4\0\10\25\2\0\2\25\2\0\26\25\1\0\7\25\1\0\1\25"+
    "\3\0\4\25\3\0\1\25\20\0\1\25\15\0\2\25\1\0\3\25"+
    "\16\0\2\25\23\0\6\25\4\0\2\25\2\0\26\25\1\0\7\25"+
    "\1\0\2\25\1\0\2\25\1\0\2\25\37\0\4\25\1\0\1\25"+
    "\23\0\3\25\20\0\11\25\1\0\3\25\1\0\26\25\1\0\7\25"+
    "\1\0\2\25\1\0\5\25\3\0\1\25\22\0\1\25\17\0\2\25"+
    "\27\0\1\25\13\0\10\25\2\0\2\25\2\0\26\25\1\0\7\25"+
    "\1\0\2\25\1\0\5\25\3\0\1\25\36\0\2\25\1\0\3\25"+
    "\17\0\1\25\21\0\1\25\1\0\6\25\3\0\3\25\1\0\4\25"+
    "\3\0\2\25\1\0\1\25\1\0\2\25\3\0\2\25\3\0\3\25"+
    "\3\0\14\25\26\0\1\25\64\0\10\25\1\0\3\25\1\0\27\25"+
    "\1\0\20\25\3\0\1\25\32\0\3\25\5\0\2\25\36\0\1\25"+
    "\4\0\10\25\1\0\3\25\1\0\27\25\1\0\12\25\1\0\5\25"+
    "\3\0\1\25\40\0\1\25\1\0\2\25\17\0\2\25\22\0\10\25"+
    "\1\0\3\25\1\0\51\25\2\0\1\25\20\0\1\25\5\0\3\25"+
    "\10\0\3\25\30\0\6\25\5\0\22\25\3\0\30\25\1\0\11\25"+
    "\1\0\1\25\2\0\7\25\72\0\60\25\1\0\2\25\14\0\7\25"+
    "\72\0\2\25\1\0\1\25\2\0\2\25\1\0\1\25\2\0\1\25"+
    "\6\0\4\25\1\0\7\25\1\0\3\25\1\0\1\25\1\0\1\25"+
    "\2\0\2\25\1\0\4\25\1\0\2\25\11\0\1\25\2\0\5\25"+
    "\1\0\1\25\25\0\4\25\40\0\1\25\77\0\10\25\1\0\44\25"+
    "\33\0\5\25\163\0\53\25\24\0\1\25\20\0\6\25\4\0\4\25"+
    "\3\0\1\25\3\0\2\25\7\0\3\25\4\0\15\25\14\0\1\25"+
    "\21\0\46\25\1\0\1\25\5\0\1\25\2\0\53\25\1\0\u014d\25"+
    "\1\0\4\25\2\0\7\25\1\0\1\25\1\0\4\25\2\0\51\25"+
    "\1\0\4\25\2\0\41\25\1\0\4\25\2\0\7\25\1\0\1\25"+
    "\1\0\4\25\2\0\17\25\1\0\71\25\1\0\4\25\2\0\103\25"+
    "\45\0\20\25\20\0\126\25\2\0\6\25\3\0\u026c\25\2\0\21\25"+
    "\1\0\32\25\5\0\113\25\6\0\10\25\7\0\15\25\1\0\4\25"+
    "\16\0\22\25\16\0\22\25\16\0\15\25\1\0\3\25\17\0\64\25"+
    "\43\0\1\25\4\0\1\25\103\0\130\25\10\0\5\25\2\0\42\25"+
    "\1\0\1\25\5\0\106\25\12\0\37\25\61\0\36\25\2\0\5\25"+
    "\13\0\54\25\4\0\32\25\66\0\27\25\11\0\65\25\122\0\1\25"+
    "\135\0\57\25\21\0\7\25\67\0\36\25\15\0\2\25\12\0\54\25"+
    "\32\0\44\25\51\0\3\25\12\0\44\25\2\0\11\25\140\0\4\25"+
    "\1\0\4\25\3\0\2\25\11\0\300\25\100\0\u0116\25\2\0\6\25"+
    "\2\0\46\25\2\0\6\25\2\0\10\25\1\0\1\25\1\0\1\25"+
    "\1\0\1\25\1\0\37\25\2\0\65\25\1\0\7\25\1\0\1\25"+
    "\3\0\3\25\1\0\7\25\3\0\4\25\2\0\6\25\4\0\15\25"+
    "\5\0\3\25\1\0\7\25\53\0\1\37\1\37\107\0\1\25\15\0"+
    "\1\25\20\0\15\25\145\0\1\25\4\0\1\25\2\0\12\25\1\0"+
    "\1\25\3\0\5\25\6\0\1\25\1\0\1\25\1\0\1\25\1\0"+
    "\4\25\1\0\13\25\2\0\4\25\5\0\5\25\4\0\1\25\64\0"+
    "\2\25\u0a7b\0\57\25\1\0\57\25\1\0\205\25\6\0\4\25\3\0"+
    "\2\25\14\0\46\25\1\0\1\25\5\0\1\25\2\0\70\25\7\0"+
    "\1\25\20\0\27\25\11\0\7\25\1\0\7\25\1\0\7\25\1\0"+
    "\7\25\1\0\7\25\1\0\7\25\1\0\7\25\1\0\7\25\120\0"+
    "\1\25\u01d5\0\2\25\52\0\5\25\5\0\2\25\4\0\126\25\6\0"+
    "\3\25\1\0\132\25\1\0\4\25\5\0\51\25\3\0\136\25\21\0"+
    "\33\25\65\0\20\25\u0200\0\u19b6\25\112\0\u51d6\25\52\0\u048d\25\103\0"+
    "\56\25\2\0\u010d\25\3\0\20\25\12\0\2\25\24\0\57\25\20\0"+
    "\37\25\2\0\106\25\61\0\11\25\2\0\147\25\2\0\44\25\1\0"+
    "\10\25\77\0\13\25\1\0\3\25\1\0\4\25\1\0\27\25\35\0"+
    "\64\25\16\0\62\25\76\0\6\25\3\0\1\25\1\0\1\25\14\0"+
    "\34\25\12\0\27\25\31\0\35\25\7\0\57\25\34\0\1\25\20\0"+
    "\5\25\1\0\12\25\12\0\5\25\1\0\51\25\27\0\3\25\1\0"+
    "\10\25\24\0\27\25\3\0\1\25\3\0\62\25\1\0\1\25\3\0"+
    "\2\25\2\0\5\25\2\0\1\25\1\0\1\25\30\0\3\25\2\0"+
    "\13\25\7\0\3\25\14\0\6\25\2\0\6\25\2\0\6\25\11\0"+
    "\7\25\1\0\7\25\1\0\53\25\1\0\12\25\12\0\163\25\35\0"+
    "\u2ba4\25\14\0\27\25\4\0\61\25\u2104\0\u016e\25\2\0\152\25\46\0"+
    "\7\25\14\0\5\25\5\0\1\25\1\0\12\25\1\0\15\25\1\0"+
    "\5\25\1\0\1\25\1\0\2\25\1\0\2\25\1\0\154\25\41\0"+
    "\u016b\25\22\0\100\25\2\0\66\25\50\0\14\25\164\0\5\25\1\0"+
    "\207\25\44\0\32\25\6\0\32\25\13\0\131\25\3\0\6\25\2\0"+
    "\6\25\2\0\6\25\2\0\3\25\43\0\14\25\1\0\32\25\1\0"+
    "\23\25\1\0\2\25\1\0\17\25\2\0\16\25\42\0\173\25\u0185\0"+
    "\35\25\3\0\61\25\57\0\40\25\20\0\21\25\1\0\10\25\6\0"+
    "\46\25\12\0\36\25\2\0\44\25\4\0\10\25\60\0\236\25\22\0"+
    "\44\25\4\0\44\25\4\0\50\25\10\0\64\25\234\0\u0137\25\11\0"+
    "\26\25\12\0\10\25\230\0\6\25\2\0\1\25\1\0\54\25\1\0"+
    "\2\25\3\0\1\25\2\0\27\25\12\0\27\25\11\0\37\25\101\0"+
    "\23\25\1\0\2\25\12\0\26\25\12\0\32\25\106\0\70\25\6\0"+
    "\2\25\100\0\1\25\17\0\4\25\1\0\3\25\1\0\33\25\54\0"+
    "\35\25\3\0\35\25\43\0\10\25\1\0\34\25\33\0\66\25\12\0"+
    "\26\25\12\0\23\25\15\0\22\25\156\0\111\25\67\0\63\25\15\0"+
    "\63\25\u0310\0\65\25\113\0\55\25\40\0\31\25\32\0\44\25\51\0"+
    "\43\25\3\0\1\25\14\0\60\25\16\0\4\25\25\0\1\25\1\0"+
    "\1\25\43\0\22\25\1\0\31\25\124\0\7\25\1\0\1\25\1\0"+
    "\4\25\1\0\17\25\1\0\12\25\7\0\57\25\46\0\10\25\2\0"+
    "\2\25\2\0\26\25\1\0\7\25\1\0\2\25\1\0\5\25\3\0"+
    "\1\25\22\0\1\25\14\0\5\25\236\0\65\25\22\0\4\25\65\0"+
    "\60\25\24\0\2\25\1\0\1\25\270\0\57\25\51\0\4\25\44\0"+
    "\60\25\24\0\1\25\73\0\53\25\125\0\32\25\u0186\0\100\25\37\0"+
    "\1\25\u01c0\0\71\25\u0107\0\11\25\1\0\45\25\21\0\1\25\61\0"+
    "\36\25\u0370\0\u039a\25\346\0\304\25\u0abc\0\u042f\25\u0fd1\0\u0247\25\u21b9\0"+
    "\u0239\25\7\0\37\25\161\0\36\25\22\0\60\25\20\0\4\25\37\0"+
    "\25\25\5\0\23\25\u0370\0\105\25\13\0\1\25\102\0\15\25\100\0"+
    "\1\25\37\0\u17ed\25\23\0\u02f3\25\u250d\0\2\25\u0bfe\0\153\25\5\0"+
    "\15\25\3\0\11\25\7\0\12\25\u1766\0\125\25\1\0\107\25\1\0"+
    "\2\25\2\0\1\25\2\0\2\25\2\0\4\25\1\0\14\25\1\0"+
    "\1\25\1\0\7\25\1\0\101\25\1\0\4\25\2\0\10\25\1\0"+
    "\7\25\1\0\34\25\1\0\4\25\1\0\5\25\1\0\1\25\3\0"+
    "\7\25\1\0\u0154\25\2\0\31\25\1\0\31\25\1\0\37\25\1\0"+
    "\31\25\1\0\37\25\1\0\31\25\1\0\37\25\1\0\31\25\1\0"+
    "\37\25\1\0\31\25\1\0\10\25\u1034\0\305\25\73\0\104\25\u04bc\0"+
    "\4\25\1\0\33\25\1\0\2\25\1\0\1\25\2\0\1\25\1\0"+
    "\12\25\1\0\4\25\1\0\1\25\1\0\1\25\6\0\1\25\4\0"+
    "\1\25\1\0\1\25\1\0\1\25\1\0\3\25\1\0\2\25\1\0"+
    "\1\25\2\0\1\25\1\0\1\25\1\0\1\25\1\0\1\25\1\0"+
    "\1\25\1\0\2\25\1\0\1\25\2\0\4\25\1\0\7\25\1\0"+
    "\4\25\1\0\4\25\1\0\1\25\1\0\12\25\1\0\21\25\5\0"+
    "\3\25\1\0\5\25\1\0\21\25\u1144\0\ua6d7\25\51\0\u1035\25\13\0"+
    "\336\25\2\0\u1682\25\u295e\0\u021e\25\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05f0\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\5\3\2\1\2\5"+
    "\3\3\1\5\1\6\1\0\5\3\2\0\1\2\2\0"+
    "\2\3\1\7\1\0\1\2\5\3\2\0\1\10\1\3"+
    "\2\0\1\2\1\3\1\11\2\3\2\12\1\2\1\0"+
    "\1\3\1\13\1\14\1\15\1\16";

  private static int [] zzUnpackAction() {
    int [] result = new int[60];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\252\0\314\0\356"+
    "\0\u0110\0\u0132\0\u0154\0\u0176\0\42\0\210\0\u0198\0\u01ba"+
    "\0\u01dc\0\u01fe\0\42\0\u0220\0\u0242\0\u0264\0\u0286\0\u02a8"+
    "\0\u02ca\0\u0154\0\u02ec\0\42\0\u030e\0\u0330\0\u0352\0\u0374"+
    "\0\146\0\u0396\0\u03b8\0\u03da\0\u03fc\0\u041e\0\u0440\0\u0462"+
    "\0\u0484\0\u04a6\0\146\0\u04c8\0\u04ea\0\u050c\0\146\0\u052e"+
    "\0\146\0\u0550\0\u0572\0\42\0\u0594\0\u05b6\0\u05b6\0\u05d8"+
    "\0\146\0\146\0\42\0\146";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[60];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\6\1\7\1\4"+
    "\1\10\1\11\3\4\1\2\1\4\1\12\1\13\1\14"+
    "\2\3\1\15\1\4\1\5\1\16\1\17\1\20\1\4"+
    "\1\21\1\22\2\23\1\0\2\23\43\0\1\3\1\24"+
    "\1\4\1\0\10\4\1\0\2\4\2\0\2\3\1\0"+
    "\1\4\2\0\4\4\7\0\1\4\1\0\1\4\1\0"+
    "\10\4\1\0\2\4\2\0\2\4\1\0\1\4\2\0"+
    "\4\4\12\0\1\5\21\0\2\5\13\0\1\4\1\0"+
    "\1\4\1\0\1\4\1\25\6\4\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\2\0\4\4\7\0\1\4\1\0"+
    "\1\4\1\0\3\4\1\26\4\4\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\2\0\4\4\7\0\1\4\1\0"+
    "\1\4\1\0\6\4\1\27\1\4\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\2\0\4\4\7\0\1\4\1\0"+
    "\1\4\1\0\5\4\1\30\2\4\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\2\0\4\4\7\0\1\4\1\0"+
    "\1\4\1\0\2\4\1\31\5\4\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\2\0\4\4\6\0\15\32\1\33"+
    "\2\32\1\34\21\32\15\35\1\36\3\35\1\0\20\35"+
    "\1\0\1\4\1\0\1\4\1\0\5\4\1\37\2\4"+
    "\1\0\2\4\2\0\2\4\1\0\1\4\2\0\4\4"+
    "\7\0\1\4\1\0\1\4\1\0\10\4\1\0\2\4"+
    "\2\0\2\4\1\0\1\4\2\0\2\4\1\40\1\4"+
    "\7\0\1\4\1\0\1\4\1\0\4\4\1\41\3\4"+
    "\1\0\2\4\2\0\2\4\1\0\1\4\2\0\4\4"+
    "\42\0\1\42\6\0\1\43\20\0\2\43\17\0\1\4"+
    "\1\0\1\4\1\0\2\4\1\44\5\4\1\0\2\4"+
    "\2\0\2\4\1\0\1\4\2\0\4\4\7\0\1\4"+
    "\1\0\1\4\1\0\1\45\7\4\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\2\0\4\4\7\0\1\4\1\0"+
    "\1\4\1\0\7\4\1\46\1\0\2\4\2\0\2\4"+
    "\1\0\1\4\2\0\4\4\7\0\1\4\1\0\1\4"+
    "\1\0\6\4\1\47\1\4\1\0\2\4\2\0\2\4"+
    "\1\0\1\4\2\0\4\4\7\0\1\4\1\0\1\4"+
    "\1\0\6\4\1\50\1\4\1\0\2\4\2\0\2\4"+
    "\1\0\1\4\2\0\4\4\13\0\2\32\2\0\1\32"+
    "\3\0\7\32\37\0\1\34\25\0\2\35\2\0\1\35"+
    "\3\0\5\35\1\51\1\52\17\0\1\4\1\0\1\4"+
    "\1\0\1\4\1\53\6\4\1\0\2\4\2\0\2\4"+
    "\1\0\1\4\2\0\4\4\7\0\1\4\1\0\1\4"+
    "\1\0\10\4\1\0\2\4\2\0\2\4\1\0\1\4"+
    "\2\0\3\4\1\54\42\0\1\55\6\0\1\43\1\0"+
    "\1\56\4\0\1\56\11\0\2\43\17\0\1\4\1\0"+
    "\1\4\1\0\3\4\1\57\4\4\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\2\0\4\4\7\0\1\4\1\0"+
    "\1\4\1\0\2\4\1\60\5\4\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\2\0\4\4\7\0\1\4\1\0"+
    "\1\4\1\0\3\4\1\61\4\4\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\2\0\3\4\1\62\7\0\1\4"+
    "\1\0\1\4\1\0\7\4\1\44\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\2\0\4\4\7\0\1\4\1\0"+
    "\1\4\1\0\6\4\1\57\1\4\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\2\0\4\4\27\0\1\34\2\52"+
    "\37\0\1\34\2\35\17\0\1\4\1\0\1\4\1\0"+
    "\6\4\1\63\1\4\1\0\2\4\2\0\2\4\1\0"+
    "\1\4\2\0\4\4\6\0\35\55\1\64\1\65\2\64"+
    "\1\55\1\0\1\66\2\0\1\67\15\0\2\66\17\0"+
    "\1\4\1\0\1\4\1\0\1\4\1\70\6\4\1\0"+
    "\2\4\2\0\2\4\1\0\1\4\2\0\4\4\7\0"+
    "\1\4\1\0\1\4\1\0\4\4\1\71\3\4\1\0"+
    "\2\4\2\0\2\4\1\0\1\4\2\0\4\4\7\0"+
    "\1\4\1\0\1\4\1\0\3\4\1\72\4\4\1\0"+
    "\2\4\2\0\2\4\1\0\1\4\2\0\4\4\43\0"+
    "\1\73\5\0\1\66\20\0\2\66\17\0\1\4\1\0"+
    "\1\4\1\0\10\4\1\0\1\4\1\74\2\0\2\4"+
    "\1\0\1\4\2\0\4\4\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1530];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\12\1\1\11\5\1\1\11\1\0\5\1"+
    "\2\0\1\11\2\0\3\1\1\0\6\1\2\0\2\1"+
    "\2\0\5\1\1\11\2\1\1\0\3\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[60];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

// This part becomes a verbatim part of the program text inside
// the class, NanoMorpho.java, that is generated.

// Definitions of tokens:
static final int ERROR = -1;

static final int NAME = 1001;
static final int LITERAL = 1002;
static final int OPNAME = 1003;

// Decleration <decl>
static final int VAR = 1010;

// Expression <expr>
static final int RETURN = 1020;
static final int WHILE = 1021;

// If Expression <ifexpr>
static final int IF = 1030;
static final int ELSIF = 1031;
static final int ELSE = 1032;

// A variable that will contain lexemes as they are recognized:
private static String lexeme;

public String getLexeme() {
  return lexeme;
}

public int getLineNumber() {
  return yyline + 1;
}

// This runs the scanner:
public static void main( String[] args ) throws Exception
{
  NanoMorpho lexer = new NanoMorpho(new FileReader(args[0]));
  int token = lexer.yylex();
  
  while(token != 0) {
    System.out.println(""+token+": \'"+lexeme+"\'");
    token = lexer.yylex();
  }
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public NanoMorpho(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2440) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return 0; }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme = yytext();
	return ERROR;
            } 
            // fall through
          case 15: break;
          case 2: 
            { lexeme = yytext();
  return LITERAL;
            } 
            // fall through
          case 16: break;
          case 3: 
            { lexeme = yytext();
  return NAME;
            } 
            // fall through
          case 17: break;
          case 4: 
            { lexeme = yytext();
  return OPNAME;
            } 
            // fall through
          case 18: break;
          case 5: 
            { lexeme = yytext();
  return yycharat(0);
            } 
            // fall through
          case 19: break;
          case 6: 
            { 
            } 
            // fall through
          case 20: break;
          case 7: 
            { lexeme = yytext();
  return IF;
            } 
            // fall through
          case 21: break;
          case 8: 
            { lexeme = yytext();
  return VAR;
            } 
            // fall through
          case 22: break;
          case 9: 
            { lexeme = yytext();
  return ELSE;
            } 
            // fall through
          case 23: break;
          case 10: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { 
            } 
            // fall through
          case 24: break;
          case 11: 
            { lexeme = yytext();
  return ELSIF;
            } 
            // fall through
          case 25: break;
          case 12: 
            { lexeme = yytext();
  return WHILE;
            } 
            // fall through
          case 26: break;
          case 13: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { 
            } 
            // fall through
          case 27: break;
          case 14: 
            { lexeme = yytext();
  return RETURN;
            } 
            // fall through
          case 28: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
